---
- name: Create AWS Security Group
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    region: ap-south-1
    vpc_id: vpc-xxxxxxxxxxxxxxxxx
    sg_name: my-ansible-sg
    description: "Security group created with Ansible"
    allowed_ports:
      - { proto: tcp, from: 22, to: 22, cidr: 0.0.0.0/0 }
      - { proto: tcp, from: 80, to: 80, cidr: 0.0.0.0/0 }
      - { proto: tcp, from: 443, to: 443, cidr: 0.0.0.0/0 }

  tasks:
    - name: Create security group
      amazon.aws.ec2_group:
        name: "{{ sg_name }}"
        description: "{{ description }}"
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        rules:
          "{{ allowed_ports }}"
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
        state: present
