---
- name: Create AWS Security Group
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    region: ap-south-1
    vpc_id: vpc-089f00b10cfbbd809
    sg_name: my-ansible-sg
    description: "Security group created with Ansible"
    allowed_ports:
      - { proto: tcp, from_port: 22, to_port: 22, cidr_ip: 0.0.0.0/0 }
      - { proto: tcp, from_port: 80, to_port: 80, cidr_ip: 0.0.0.0/0 }
      - { proto: tcp, from_port: 443, to_port: 443, cidr_ip: 0.0.0.0/0 }
      - { proto: tcp, from_port: 8080, to_port: 8080, cidr_ip: 0.0.0.0/0 }
  tasks:
    - name: Create security group
      amazon.aws.ec2_group:
        name: "{{ sg_name }}"
        description: "{{ description }}"
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        rules: "{{ allowed_ports }}"
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
        state: present
